### ISSUE TITLE
Archiving a project with BeastComponents framework

### ISSUE THREAD

**Issue by aornano** [istsest/BeastComponents#2]
Everytime I try to archive a project with this framework, Xcode give me the following errors:

`ld: bitcode bundle could not be generated because '/<myproject...>/BeastComponents/BeastComponents.framework/BeastComponents' was built without full bitcode...`

**Comment by istsest** [comment]
Hi @aornano 

Thanks for using Beast Components and sorry about late response.

Can you try setting bit code disable in build settings?
If you need to use bit code, please let me know by leaving a comment here.

Joon.

**Comment by aornano** [comment]
Yes I've tried also with bit code disabled, but Apple don't validate the project, it report some errors around this framework (compiled with Xcode 9.1 , Swift 4.0.2)  so I can't test it to the test flight process.

**Comment by istsest** [comment]
Hi @aornano 

I just created a new swift project with single view controller on Xcode 9.1 and it succeeded to build and upload it including the framework through Cocoapod onto Testflight with bit code disabled. Can you give me information in detail, such as exact error messages or screenshots, please? 

Joon.

**Comment by aornano** [comment]
I'm sorry istsest, I decide to switch to another solution so I've removed Beast Components to use iCarousel with source. I think my issue is related to the SDK used to compile Beast Components, have you compiled it with XCode 8.x?
