### ISSUE TITLE
Card view gets hidden while scrolling 

### ISSUE THREAD

**Issue by asifbilal786** [istsest/BeastComponents#3]
In example project, if I set coverFlow style to bottom as given below.

> self.coverFlowView.coverFlowStyle = .bottom

Some of the card views get hidden when scroll through all cards.

Please resolve this issue or alternatively provide the source code so that I can do it myself.

**Comment by istsest** [comment]
Fixed the issue.
Thank you for the report.

**Comment by asifbilal786** [comment]
You welcome @istsest .
If you don't mind, can we have your source code. This component is really nice work from you, but i need to have some customization in this component. Can you provide the source code in this regard?

**Comment by istsest** [comment]
Sorry I can't.
